[package]
name = "common"
edition = "2024"
version.workspace = true
authors.workspace = true

[dependencies]
env_logger = "0.11.8"
log = "0.4.28"
pnet = { workspace = true }

[lib]
src = "src/lib.rs"
